// <auto-generated />
using System;
using InfastructureProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InfastructureProject.Migrations
{
    [DbContext(typeof(BinarySearchTreeContext))]
    [Migration("20210915140821_BinarySearchTreeCTX")]
    partial class BinarySearchTreeCTX
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BinaryTree.EntitiesProject.Entities.Tree", b =>
                {
                    b.Property<int>("TreeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("LeftId")
                        .HasColumnType("int");

                    b.Property<int?>("RightId")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("TreeId");

                    b.HasIndex("LeftId");

                    b.HasIndex("RightId");

                    b.ToTable("Tree");
                });

            modelBuilder.Entity("BinaryTree.EntitiesProject.Entities.Tree", b =>
                {
                    b.HasOne("BinaryTree.EntitiesProject.Entities.Tree", "Left")
                        .WithMany()
                        .HasForeignKey("LeftId");

                    b.HasOne("BinaryTree.EntitiesProject.Entities.Tree", "Right")
                        .WithMany()
                        .HasForeignKey("RightId");

                    b.Navigation("Left");

                    b.Navigation("Right");
                });
#pragma warning restore 612, 618
        }
    }
}
